language: smalltalk
sudo: false

os:
  - linux
  - osx

smalltalk:
  - Squeak-trunk
  - Squeak-5.1

install:
  - chmod -R 777 $TRAVIS_BUILD_DIR/build-support/*.sh
  - $TRAVIS_BUILD_DIR/build-support/copyfonts.sh
